
##########################################
#     Change these variables !important
##########################################

# Set this for Copyright in the footer
owner: Sarah Tabassum

# Optional quote in the footer
# To disable set enable to false
quote:
  enable: true
  quote: Everyday struggle to be better than yesterday!
  author: unknown

# Set this to your main site title. If page doesn't have its own title,
# then this title will be used.
title: Sarah Tabassum


# Following needed for disqus integration
# Set your 'disqus' account name
disqus: sarahtabassum-com

# Uncomment if deployed locally
#url: http://127.0.0.1:4000/:4000

# Set your host if deployed not locally
# For example "https://yourGitHub.github.io"
url:https://sarahtabassum.com

# Change this to your base URL starting with forward slash if site is in gh-pages branch
# For example /branchName
# NOTE! only change if site is NOT in master's branch
baseurl:

# Change this to your google analytics ID
google_analytics:

# Contact form pupublic key
contact_PK:

##########################################
#          Optional variables
##########################################

# Set maximum posts per page
paginate: 5

# Set permalink
permalink: /:categories/:title

# MathJax support
math: true

collections:
- definitions

##########################################
#          Do not change these variables
##########################################

include:
  - _pages

sass:
  sass_dir: _sass
sass:
    style: compressed

gems:
  - jekyll-paginate
  - jekyll-sitemap # add /sitemap.xml file

paginate_path: /_pages/page:num

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
